src/GrandeGift/Models/Hamper.cs
namespace GrandeGift.Models
{
    public class Hamper
    {
        public int HamperId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string Picture { get; set; }       
        public double Price { get; set; }
        public int Hidden { get; set; }
        // one category - many products
        public int CategoryId { get; set; }
    }
}

src/GrandeGift/Controllers/HamperController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GrandeGift.Services;
using GrandeGift.Models;
using GrandeGift.ViewModels;
using Microsoft.AspNetCore.Authorization;
// these namespaces for uploading picture and creating subfolder (dynamically)
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;



namespace GrandeGift.Controllers
{
    public class HamperController : Controller
    {
        private IDataService<Category> _categoryDataService;
        private IDataService<Hamper> _hamperDataService;
        private IHostingEnvironment _environment;

        public HamperController(IDataService<Category> categoryService, IDataService<Hamper> hamperService,
            IHostingEnvironment envService)
        {
            _categoryDataService = categoryService;
            _hamperDataService = hamperService;
            _environment = envService;
        }

        //(Admin) Create hamper
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HamperCreateViewModel vm, IFormFile file)
        {
            int theCategoryId = int.Parse(TempData["catId"].ToString());
            if (ModelState.IsValid)
            {
                Hamper hamper = new Hamper
                {
                    Name = vm.Name,
                    Details = vm.Details,
                    Price = vm.Price,
                    CategoryId = theCategoryId
                };
                //if file is to be uploaded
                if (file != null)
                {
                    //upload server-side path
                    var uploadPath = Path.Combine(_environment.WebRootPath, "uploads");
                    //create folder with username (dynamically). If folder already exists - no code executed
                    Directory.CreateDirectory(Path.Combine(uploadPath, User.Identity.Name));                    
                    string fileName = FileNameHelper.GetNameFormat(file.FileName);
                    //copy file from client side to server
                    using (var fileStream = new FileStream(Path.Combine(uploadPath, User.Identity.Name, fileName), FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }
                    //add path to the database (category object)
                    hamper.Picture = User.Identity.Name + "/" + fileName;
                }// end file is to be uploaded

                _hamperDataService.Create(hamper);
                return RedirectToAction("Details", "Category", new { id = theCategoryId });
            }
            return View(vm);
        }

        //Details page
        public IActionResult Details(int id)
        {
            //get the single category from DB
            Hamper hamper = _hamperDataService.GetSingle(h => h.HamperId == id);

            HamperDetailsViewModel vm = new HamperDetailsViewModel
            {
                HamperId = hamper.HamperId,
                Name = hamper.Name,
                Details = hamper.Details,
                Price = hamper.Price,
                Picture = hamper.Picture
            };

            return View(vm);
        }

        //(admin) Update hamper
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Update(int id)
        {
            Hamper hamper = _hamperDataService.GetSingle(h => h.HamperId == id);
            HamperUpdateViewModel vm = new HamperUpdateViewModel
            {
                HamperId = hamper.HamperId,
                Name = hamper.Name,
                Details = hamper.Details,
                Price = hamper.Price,
                Hidden = hamper.Hidden!=0,
                Picture = hamper.Picture
            };
            return View(vm);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(HamperUpdateViewModel vm, IFormFile file)
        {
            int theCategoryId = int.Parse(TempData["catId"].ToString());
            if (ModelState.IsValid)
            {
                Hamper hamp = new Hamper
                {
                    HamperId = vm.HamperId,
                    Name = vm.Name,
                    Details = vm.Details,
                    Price = vm.Price,
                    Hidden = vm.Hidden ? 1:0,
                    Picture = vm.Picture,
                    CategoryId = theCategoryId
                };
                //if file is to be uploaded
                if (file != null)
                {
                    //upload server-side path
                    var uploadPath = Path.Combine(_environment.WebRootPath, "uploads");
                    //create folder with username (dynamically). If folder already exists - no code executed
                    Directory.CreateDirectory(Path.Combine(uploadPath, User.Identity.Name));                    
                    string fileName = FileNameHelper.GetNameFormat(file.FileName);
                    //copy file from client side to server
                    using (var fileStream = new FileStream(Path.Combine(uploadPath, User.Identity.Name, fileName), FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }
                    //add path to the database (category object)
                    hamp.Picture = User.Identity.Name + "/" + fileName;
                }// end file is to be uploaded

                _hamperDataService.Update(hamp);
                return RedirectToAction("Details", "Category", new { id = theCategoryId });
            }
            return View(vm);
        }
    }
}

src/GrandeGift/Views/Hamper/Create.cshtml
@model HamperCreateViewModel

<div style="width: 30%">
    <h5>Create Hamper</h5>

    <form asp-controller="Hamper" asp-action="Create" method="post" enctype="multipart/form-data" asp-anti-forgery="true">

        <div asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            <label asp-for="Name">Hamper name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name"></span> 
        </div>

        <div class="form-group">
            <label asp-for="Details">Hamper details</label>
            <input asp-for="Details" class="form-control" />
            <span asp-validation-for="Details"></span> 
        </div>

        <div class="form-group">
            <label asp-for="Price">Hamper price, AUD</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price"></span> 
        </div>

        <div class="form-group">
            <label asp-for="Picture">Hamper Picture</label>
            <input type="file" name="file" class="form-control-file" />
        </div>

        <div>
            <input type="submit" class="btn btn-primary" value="Save" />
            <a class="btn btn-light" href="/Home/Index" role="button">Cancel</a>
        </div>
    </form>
</div>

src/GrandeGift/Views/Hamper/Details.cshtml
@model HamperDetailsViewModel

<div class="row">
    <div class="col-sm-6">
        <img src="~/uploads/@Model.Picture" class="img-fluid" style="width:100%" alt="@Model.Picture">
    </div>

    <div class="col-sm-6">
        <div class="container text-center">
            <h4>@Model.Name</h4>
        </div>
        <div class="container">
            <p><b>Price: &#x24;@Model.Price</b></p>
        </div>
        <div class="container">
            <p>Hamper includes:</p>
            <ul>
                @foreach (string line in Model.Details
                .Split(new[] { ";" }, StringSplitOptions.RemoveEmptyEntries))
                {
                    <li>@line</li>
                }
            </ul>
        </div>
        @if (!User.IsInRole("Admin"))
        {
            @Html.ActionLink("Buy", "Cart", "Order", new { hamperId = Model.HamperId },
            new Dictionary<string, object> { { "class", "btn btn-primary mb-2" } })

        }
    </div>
</div>

src/GrandeGift/Views/Hamper/Update.cshtml
@model HamperUpdateViewModel

<div style="width: 30%">
    <h5>Update Hamper</h5>

    <form asp-controller="Hamper" asp-action="Update" method="post" enctype="multipart/form-data" asp-anti-forgery="true">

        <div asp-validation-summary="ModelOnly"></div>

        <div>
            <input asp-for="HamperId" hidden />
        </div>

        <div class="form-group">
            <label asp-for="Name">Hamper name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name"></span> 
        </div>

        <div class="form-group">
            <label asp-for="Details">Hamper details</label>
            <input asp-for="Details" class="form-control" />
            <span asp-validation-for="Details"></span> 
        </div>

        <div class="form-group">
            <label asp-for="Price">Hamper price, AUD</label>
            <input asp-for="Price" class="form-control" />
            <span asp-validation-for="Price"></span> 
        </div>

        @if (Model.Picture != null)
        {
            <div class="form-group">
                <label asp-for="Picture">Hamper picture</label>
                <input asp-for="Picture" class="form-control" readonly />
            </div>
        }
        @if (Model.Picture == null)
        {
            <div class="form-group">
                <label asp-for="Picture">Hamper picture</label>
                <input type="file" name="file" class="form-control-file" />
            </div>
        }

        <div class="form-check">
            <label asp-for="Hidden" class="form-check-label">
                <input asp-for="Hidden" type="checkbox" class="form-check-input">
                Hidden from customer
            </label>
        </div>

        <div>
            <input type="submit" class="btn btn-primary" value="Save changes" />
            <a class="btn btn-light" href="/Home/Index" role="button">Cancel</a>
        </div>
    </form>
</div>